---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-1replica
provisioner: driver.longhorn.io
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
