---
name: PR build
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [arm64-dirty, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build packages
        env:
          PR_ID: ${{ github.event.pull_request.number  }}
        run: |
          make V=1 pkgs
          COMMIT_ID=$(git describe --abbrev=8 --always)
          echo "VERSION=0.0.0-pr$PR_ID-$COMMIT_ID" >> $GITHUB_ENV
          echo "TAG=evebuild/danger:pr$PR_ID" >> $GITHUB_ENV
      - name: Build EVE for Xen
        run: |
          make V=1 ROOTFS_VERSION="$VERSION" HV=xen eve
      - name: Build EVE for KVM
        run: |
          rm -rf dist
          make V=1 ROOTFS_VERSION="$VERSION" HV=kvm eve
      - name: Export docker container
        run: |
          ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/')
          echo "ARCH=$ARCH" >> "$GITHUB_ENV"
          for i in xen kvm; do
             docker tag "lfedge/eve:$VERSION-$i" "$TAG-$i-$ARCH"
             IMGS="$IMGS $TAG-$i-$ARCH"
          done
          docker save $IMGS > eve.tar
      - name: Upload EVE
        uses: actions/upload-artifact@v2
        with:
          name: eve-${{ env.ARCH }}
          path: eve.tar
